name: Deploy to Aliyun

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Aliyun server
        uses: appleboy/ssh-action@master
        with:
          host: 120.26.248.32
          username: root
          key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
          script: |
            # Create work directory if it doesn't exist
            mkdir -p /root/website-analyzer

            # Navigate to work directory
            cd /root/website-analyzer

            # If repo exists, pull latest changes, otherwise clone it
            if [ -d ".git" ]; then
              git pull
            else
              git clone https://github.com/Yangeyu/website-analyzer.git .
            fi

            # Build the Docker image
            docker build -t website-analyzer .

            # Stop and remove any existing container with the same name
            docker stop website-analyzer-container || true
            docker rm website-analyzer-container || true

            # Run the Docker container
            docker run -d --name website-analyzer-container \
              -p 8000:8000 \
              --restart unless-stopped \
              website-analyzer
            
            # Check if the container is running
            docker ps | grep website-analyzer-container
